### ISSUE TITLE
Moved to GitLab?

### ISSUE THREAD

**Issue by hendursaga** [concat-fuse/concat-fuse#1]
Under "about" it says that "concat-fuse moved to https://gitlab.com/concat-fuse/concat-fuse" but when I click the link, it gives a 404 error. I see that [the last commit](https://github.com/concat-fuse/concat-fuse/commit/5a4e23e21bc96898bd7b3488fd8fdc812d133e74) removed `.gitlab-ci.yml`. Does that mean that GitHub is back to being the official hub?

**Comment by Grumbel** [comment]
It's back on GitHub. I fixed the About.
